Repository LLNL/Surfactant, pull requests merged in 2023-11, with the labels that each got.

#51 Cyt 479 stat subscommand functionality
  surfactant/cmd/stat.py
Labels: enhancement

#74 Ensure a non-NoneType value exists for metadata in stat subcommand
  surfactant/cmd/stat.py
Labels: bug

#57 Plugin string extractor
  .gitignore
  surfactantplugin-binary2strings/README.md
  surfactantplugin-binary2strings/pyproject.toml
  surfactantplugin-binary2strings/surfactantplugin_binary2strings.py
Labels: plugins

#58 Plugin angr
  .gitignore
  surfactant/cmd/generate.py
  surfactantplugin-angrimportfinder/README.md
  surfactantplugin-angrimportfinder/pyproject.toml
  surfactantplugin-angrimportfinder/surfactantplugin_angrimportfinder.py
Labels: plugins

#54 Added support for ImplMap entries and relationships for .NET binaries
  surfactant/infoextractors/pe_file.py
  surfactant/relationships/_internal/windows_utils.py
  surfactant/relationships/dotnet_relationship.py
Labels: enhancement
