Repository LLNL/Surfactant, pull requests merged in 2023-08, with the labels that each got.

#22 Add scripts and instructions for setting up a workflow to work with windows installers
  docs/windows_installer_tutorial/AutomatedInstallerWorkflowSetup.md
  docs/windows_installer_tutorial/execinstaller.py
  docs/windows_installer_tutorial/fsfilter.patch
  docs/windows_installer_tutorial/setupstepper.py
Labels: documentation, enhancement

#31 Fix no StringTable Attribute
  surfactant/cmd/generate.py
  surfactant/infoextractors/pe_file.py
Labels: bug

#29 Cyt 444 more unit tests
  tests/data/a_out_files/big_m68020.aout
  tests/data/a_out_files/big_netbsd_i386.aout
  tests/data/a_out_files/big_netbsd_sparc.aout
  tests/data/a_out_files/little_386.aout
  tests/data/a_out_files/little_unknown.aout
  tests/data/coff_files/intel_80386_coff
  tests/file_types/test_a_out_files.py
  tests/file_types/test_file_magic.py
  tests/relationships/test_dotnet.py
  tests/relationships/test_pe.py
  tests/symlink/resolve_links.py
  tests/symlink/test_resolve_links.py
Labels: testing

#21 Set up ReadTheDocs structure
  docs/changelog.md
  docs/conf.py
  docs/config.md
  docs/contribute.md
  docs/getstarted.md
  docs/index.md
  docs/plugins.md
  docs/usage.md
Labels: documentation
