Repository LLNL/Surfactant, pull requests merged in 2023-07, with the labels that each got.

#3 Update SPDX output writer docstrings
  surfactant/output/spdx_writer.py
Labels: documentation

#5 Add workflow for publishing releases on PyPI
  .github/workflows/release.yml
Labels: github_actions

#10 Update Python packaging metadata and add additional badges to README
  README.md
  pyproject.toml
Labels: documentation

#14 Implement portable posix path normalization
  surfactant/relationships/_internal/posix_utils.py
  surfactant/relationships/elf_relationship.py
  tests/relationships/test_posix_utils.py
Labels: bug, enhancement

#16 Use cross-platform consistent pathlib for joining paths instead of os.path for ELF relationships
  surfactant/relationships/elf_relationship.py
Labels: bug

#15 Enable Windows CI builds
  .github/workflows/pytest.yml
Labels: github_actions

#17 Add Java support
  pyproject.toml
  surfactant/infoextractors/java_file.py
  surfactant/plugin/manager.py
  surfactant/relationships/java_relationship.py
  tests/relationships/test_java.py
Labels: enhancement
