Repository LLNL/Surfactant, pull requests merged in 2023-12, with the labels that each got.

#83 CYT 659 support dynamic list to analyze
  surfactant/__init__.py
  surfactant/cmd/generate.py
  surfactant/config.py
  surfactant/plugin/hookspecs.py
Labels: enhancement

#91 Add GitHub PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#94 CYT-691 added cli command and add, find, edit subcommand stubs
  surfactant/__main__.py
  surfactant/cmd/cli.py
Labels: enhancement

#95 Add docstrings to fileinfo and merge SBOM scripts
  scripts/merge_sbom.py
  surfactant/fileinfo.py
Labels: documentation

#98 Update name of logo file to use for RTD
  docs/conf.py
Labels: bug, documentation

#90 Fill in remaining TODOs and clean-up documentation
  README-PLUGIN.md
  README.md
  docs/basic_usage.md
  docs/changelog.md
  docs/configuration_files.md
  docs/contribute.md
  docs/contribution_guide.md
  docs/getting_started.md
  docs/index.md
  docs/plugins.md
Labels: documentation

#40 Cyt 383 support running external tools syft
  surfactant/cmd/generate.py
  surfactant/plugin/hookspecs.py
  surfactantplugin-syft/README.md
  surfactantplugin-syft/pyproject.toml
  surfactantplugin-syft/surfactantplugin_syft.py
Labels: enhancement
