Repository LLNL/Surfactant, pull requests merged in 2024-01, with the labels that each got.

#106 Add plugins subfolder
  docs/plugins.md
  plugins/README.md
  plugins/angrimportfinder/README.md
  plugins/angrimportfinder/pyproject.toml
  plugins/angrimportfinder/surfactantplugin_angrimportfinder.py
  plugins/binary2strings/README.md
  plugins/binary2strings/pyproject.toml
  plugins/binary2strings/surfactantplugin_binary2strings.py
  plugins/checksec.py/README.md
  plugins/checksec.py/pyproject.toml
  plugins/checksec.py/surfactantplugin_checksec.py
  plugins/syft/README.md
  plugins/syft/pyproject.toml
  plugins/syft/surfactantplugin_syft.py
Labels: plugins

#107 Add 'cyclonedx' short name for CycloneDX output writer
  surfactant/output/cyclonedx_writer.py
Labels: bug

#110 Updated .toml file with older CycloneDX version
  pyproject.toml
Labels: dependencies
