Repository LLNL/Surfactant, pull requests merged in 2024-10, with the labels that each got.

#184 CYT 341 Add basic Mach-O file info extractor
  README.md
  docs/configuration_files.md
  docs/getting_started.md
  docs/index.md
  docs/settings.md
  pyproject.toml
  surfactant/infoextractors/__macho_cpuSubtypes.py
  surfactant/infoextractors/mach_o_file.py
  surfactant/plugin/manager.py
Labels: enhancement

#244 Add support for extract paths being files
  surfactant/cmd/generate.py
  surfactant/infoextractors/mach_o_file.py
  surfactant/sbomtypes/_sbom.py
  surfactant/sbomtypes/_software.py
Labels: bug, enhancement

#265 Fix issues identified by mypy
  surfactant/cmd/config.py
  surfactant/cmd/generate.py
  surfactant/cmd/merge.py
  surfactant/configmanager.py
  surfactant/infoextractors/elf_file.py
  surfactant/infoextractors/java_file.py
  surfactant/infoextractors/js_file.py
  surfactant/infoextractors/mach_o_file.py
  surfactant/infoextractors/ole_file.py
  surfactant/infoextractors/pe_file.py
  surfactant/plugin/hookspecs.py
  surfactant/plugin/manager.py
  surfactant/relationships/dotnet_relationship.py
  surfactant/relationships/elf_relationship.py
  surfactant/relationships/java_relationship.py
  surfactant/sbomtypes/_analysisdata.py
  surfactant/sbomtypes/_sbom.py
Labels: bug
