Repository LLNL/Surfactant, pull requests merged in 2025-01, with the labels that each got.

#201 Add options to merge command for controlling creation of system entry and type of relationships
  surfactant/cmd/merge.py
  tests/cmd/test_merge.py
Labels: enhancement

#321 Add information to docs showing overview of how Surfactant works
  docs/conf.py
  docs/getting_started.md
  docs/images.toml
  docs/index.md
  docs/internals_overview.md
  docs/requirements.txt
Labels: documentation

#328 fix: crash when checking zlib magic bytes on empty or 1-byte files
  surfactant/filetypeid/id_magic.py
Labels: bug

#326 feat: Add configuration option to enable/disable Docker Scout
  README.md
  docs/settings.md
  surfactant/infoextractors/docker_image.py
Labels: enhancement

#287 Add TUI for creating/modifying config files.
  README.md
  pyproject.toml
  surfactant/__main__.py
  surfactant/cmd/config_tui.py
  surfactant/web-files/config_tui.tcss
Labels: enhancement

#327 feat: Enhance JS database management with hashing and timestamp functionality
  surfactant/database_manager/__init__.py
  surfactant/database_manager/database_utils.py
  surfactant/infoextractors/js_file.py
Labels: enhancement
