Repository LLNL/Surfactant, pull requests merged in 2025-03, with the labels that each got.

#370 docs: update specimen configuration and ContextEntry options
  README.md
  docs/configuration_files.md
  surfactant/config.py
Labels: documentation

#372 ci: set default workflow permissions
  .github/workflows/pytest.yml
  .github/workflows/release.yml
Labels: github_actions

#363 feat: Add support for (legacy) U-Boot/uImage file headers
  surfactant/filetypeid/id_magic.py
  surfactant/infoextractors/uimage_file.py
  surfactant/plugin/manager.py
  tests/data/uimage_files/README.md
  tests/data/uimage_files/bad1.img
  tests/data/uimage_files/hello_world.img
  tests/file_types/test_uimage_files.py
Labels: enhancement

#374 feat: support plugin hints for software entry fields
  surfactant/cmd/generate.py
  surfactant/infoextractors/ole_file.py
  surfactant/infoextractors/pe_file.py
  surfactant/infoextractors/uimage_file.py
  surfactant/plugin/hookspecs.py
  tests/file_types/test_uimage_files.py
Labels: enhancement

#376 add current_context variable to extract_file_info hook
  surfactant/cmd/generate.py
  surfactant/infoextractors/file_decompression.py
  surfactant/plugin/hookspecs.py
Labels: enhancement

#353 CI Workflow for 3rd-Party Plugins
  .github/workflows/test_plugins.yml
  plugins/grype/pyproject.toml
  plugins/grype/surfactantplugin_grype.py
  plugins/grype/tests/test_grype.py
  surfactant/cmd/plugin.py
  surfactant/plugin/manager.py
Labels: testing
