Repository LLNL/Surfactant, pull requests merged in 2025-02, with the labels that each got.

#261 Adding basic framework for the CLI, no changes to old cli.
  docs/cli_usage.md
  surfactant/__main__.py
  surfactant/cmd/cli.py
  surfactant/cmd/cli_commands/__init__.py
  surfactant/cmd/cli_commands/cli_base.py
  surfactant/cmd/cli_commands/cli_load.py
  surfactant/cmd/cli_commands/cli_save.py
  tests/cmd/test_cli.py
Labels: enhancement

#346 docs: Add core.include_all_files to list of settings
  docs/settings.md
Labels: documentation

#347 fix: Specimen config includeAllFiles option being ignored
  docs/configuration_files.md
  surfactant/cmd/generate.py
Labels: bug

#357 add parens in ftype condition
  surfactant/cmd/generate.py
Labels: bug
